### ISSUE TITLE
'.../input_decks/$RUN_NAME.tar' creation on validation run

### ISSUE THREAD

**Issue by ma-th** [lautenberger/elmfire#12]
the single fire validation run process seems to work and provides some fire model outputs but gives an error on creation of the tarred input deck 'elmfire/runs/hindcasts/input_decks/$RUN_NAME.tar', which is an issue later when trying to run the hindcast via the 
01-run.sh script. See lines 11-13 of the hindcast run log attached. 

[ca-county_20180701_062200.txt](https://github.com/lautenberger/elmfire/files/11740595/ca-county_20180701_062200.txt)

The log message appears to be commanded from '/elmfire/runs/hindcasts/04-launch_run.sh'  lines 141-142:
> progress_message` "Done setting up, tarring up input deck"
> tar -cf $CWD/input_decks/$RUN_NAME.tar ./*

**Comment by ma-th** [comment]
this was run using the latest release 2023.06

**Comment by lautenberger** [comment]
Thank you Maria! Acknowledging receipt and will take a look here shortly.

**Comment by lautenberger** [comment]
The error message is emitted by `tar` most likely because the directory `$ELMFIRE_BASE_DIR/runs/hindcasts/input_decks` does not exist which on your machine.  I committed a `.gitignore` file to the repo in that directory and that should solve the problem moving forward:

https://github.com/lautenberger/elmfire/tree/main/runs/hindcasts/input_decks

So either `git pull` or `mkdir` that directory and I suspect the case will run to completion. If that solves it let me know so I can close out this ticket - thanks!

**Comment by ma-th** [comment]
working without the `tar` error message now. thanks!

**Comment by lautenberger** [comment]
Excellent - will close this ticket then. And if you happen to notice any typos or weirdness in the documentation as you're going through it, feel free to submit a PR to get it cleaned up. Thanks!
