### ISSUE TITLE
The use of CYCLE

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#28]
I tried using 

IF ((LB_P%IX .LT. IX_LOW_BORDER) .OR. (LB_P%IY .LT. IY_LOW_BORDER) .OR. (LB_P%IX .GT. IX_HIGH_BORDER) .OR. (LB_P%IY .GT. IY_HIGH_BORDER)) THEN
     CYCLE
ENDIF 

instead of

   IF ((LB_P%IX .GE. IX_LOW_BORDER) .AND. (LB_P%IY .GE. IY_LOW_BORDER) .AND. (LB_P%IX .LE. IX_HIGH_BORDER) .AND. (LB_P%IY .LE. IY_HIGH_BORDER)) THEN
.
.
.
ENDIF

to limit the effect of radiation and DFC.

But the results are different. I expect them to be the same since I believe they are doing the same thing

**Comment by lautenberger** [comment]
Hmmm, `CYCLE` will drop you out of the current iteration of a loop. Did you want to `CONTINUE` instead? That will just do nothing. See https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn83/index.html for example. This is somewhat confusing since in BASH `continue` drops you out of the current loop iteration.

**Comment by lautenberger** [comment]
Hi Dwi - I'm closing this issue, reopen if something's not clear - thanks!
