### ISSUE TITLE
Simulation stop halfway before reaching TSTOP

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#32]
When I run for 30hr, most of the time it only gives the result until 15hr. The input deck is the following.

https://drive.google.com/file/d/1YtfXC3v-L7JPomIBeyAVtQoGsqkjhsWE/view?usp=sharing

**Comment by lautenberger** [comment]
Thanks Dwi, I'm looking into it

**Comment by lautenberger** [comment]
Dwi- I launched this run 2 days ago and it's still chugging along, albeit very slowly. I don't think there's a bug here, I think it's just taking a very long time to run. 

I had ELMFIRE dump intermediate timings and about 99.99% of CPU time is spent in the urban spread routines. Let's spend some time to get these run times down when urban spread is enabled, it will pay off in the long run. Have you done any profiling of the urban spread routines with Intel Vtune Profiler or similar?

**Comment by dwimjpurnomo** [comment]
Yes, Thomas fire was very long even with Hamada, so it will be even longer with the new model.
I will try Intel Vtune Profiler.

**Comment by dwimjpurnomo** [comment]
I am currently using a virtual machine for vtune, because my PC has windows OS. Attached is the message that I cannot have analysis on memory access. Is that OK?
![vtune](https://github.com/lautenberger/elmfire/assets/38124875/23e42dfe-55f6-479a-9878-6c071ce0522e)

**Comment by lautenberger** [comment]
Hi Dwi- I just checked and this case ran to completion locally. It took about 3 days, Sep 9 - Sep 12.  So I'm going to close this issue and let's move the optimization/profiling discussion over to Issue #16. Based on the above screen shot It seems like Vtune is saying it can't do GPU hotspots which doesn't matter since ELMFIRE doesn't use GPU for anything. Not sure about the memory access failure though.
