### ISSUE TITLE
Missing burn_probability.tif file in Outputs

### ISSUE THREAD

**Issue by NogaGivoli** [lautenberger/elmfire#42]
Hi Chris,

In an attempt to compute burn probability, I defined CALCULATE_BURN_PROBABILITY = .TRUE. in the elmfire.data.in file of tutorial 04 together with a few other configurations. No errors occurred but the burn_probability.tif file was not created. Only head_fire_flame_length and head_fire_spread_rate files were generated. 
I am attaching the elmfire.data.in file that I used. 
For running, I used just the ./01-run.sh command of Tutorial 04: Landscape-scale fire potential.

[elmfire_data_in.txt](https://github.com/lautenberger/elmfire/files/13198352/elmfire_data_in.txt)

**Comment by lautenberger** [comment]
Noga,

The keyword `CALCULATE_BURN_PROBABILITY` has been deprecated in favor of 'CALCULATE_TIMES_BURNED' because they’re redundant. Annual burn probability is times burned divided by the number of years of ignitions simulated. So if you construct your spatial and temporal ignition patterns to represent the expected number of ignitions in say 100,000 years, then annual burn probability is 1e-5*times burned.  

A hotfix is forthcoming that will throw an error message if `CALCULATE_BURN_PROBABILITY = .TRUE.` but for now make sure you run with `CALCULATE_BURN_PROBABILITY = .FALSE.` convert times burned to burn probability outside of ELMFIRE.

**Comment by NogaGivoli** [comment]
Great, will do, many thanks!

**Comment by NogaGivoli** [comment]
Hello again, 
Just to clarify, can I deduce the burned times by utilizing either "head_fire_flame_length" or "head_fire_spread_rate"? For example, would it be enough to establish that any pixel with a value of 0 head_fire_flame_length is considered unburnt, while anything above 0 is considered burnt?

**Comment by lautenberger** [comment]
Yes, although I've never thought of it in that way, I believe that would work. The limitation is that you would have to ensure that the outputs are being written for every ensemble member.
